# GitHub funding configuration
# Docs: https://docs.github.com/sponsors/receiving-sponsorships-through-github-sponsors/adding-a-sponsor-button-to-your-repository

custom:
  - "https://paypal.me/mdm535"
